"""add unique active source url index

Revision ID: 21432cdf978f
Revises: 94f350d270a4
Create Date: 2026-03-24 20:00:49.955605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21432cdf978f'
down_revision: Union[str, Sequence[str], None] = '94f350d270a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index('uq_source_urls_url_active', 'source_urls', ['url'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_source_urls_url_active', table_name='source_urls', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
