"""initial schema with soft delete

Revision ID: 50e1159260e2
Revises:
Create Date: 2026-03-19 22:29:31.664191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "50e1159260e2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "completed", "failed", name="crawl_job_status"),
            server_default="running",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "crawler", "api", "user_submission", "partner_feed", name="source_type"
            ),
            nullable=False,
        ),
        sa.Column(
            "trust_level",
            sa.Numeric(precision=2, scale=1, asdecimal=False),
            nullable=True,
        ),
        sa.Column("disabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("default_tags", postgresql.ARRAY(sa.Text()), nullable=True),
        sa.Column("crawl_frequency", sa.Integer(), nullable=False),
        sa.Column(
            "crawl_frequency_locked",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("crawl_after", sa.Date(), nullable=True),
        sa.Column("force_crawl", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(), nullable=True),
        sa.Column(
            "crawl_mode",
            sa.Enum("browser", "json_api", name="crawl_mode"),
            server_default="browser",
            nullable=False,
        ),
        sa.Column("selector", sa.String(length=500), nullable=True),
        sa.Column("num_clicks", sa.Integer(), nullable=True),
        sa.Column("js_code", sa.Text(), nullable=True),
        sa.Column("keywords", sa.String(length=255), nullable=True),
        sa.Column("max_pages", sa.Integer(), server_default="30", nullable=False),
        sa.Column("max_batches", sa.Integer(), nullable=True),
        sa.Column(
            "json_api_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("delay_before_return_html", sa.Integer(), nullable=True),
        sa.Column(
            "content_filter_threshold",
            sa.Numeric(precision=3, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column("scan_full_page", sa.Boolean(), nullable=True),
        sa.Column("remove_overlay_elements", sa.Boolean(), nullable=True),
        sa.Column("javascript_enabled", sa.Boolean(), nullable=True),
        sa.Column("text_mode", sa.Boolean(), nullable=True),
        sa.Column("light_mode", sa.Boolean(), nullable=True),
        sa.Column("use_stealth", sa.Boolean(), nullable=True),
        sa.Column(
            "scroll_delay",
            sa.Numeric(precision=3, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column("crawl_timeout", sa.Integer(), nullable=True),
        sa.Column("process_images", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_table(
        "source_urls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("js_code", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_contents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_result_id", sa.Integer(), nullable=False),
        sa.Column("crawled_content", sa.Text(), nullable=True),
        sa.Column("extracted_content", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crawl_result_id"], ["crawl_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crawl_result_id"),
    )
    op.create_table(
        "extracted_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_result_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("emoji", sa.String(length=10), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("sublocation", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column(
            "occurrences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_result_id"], ["crawl_results.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("idx_grantees_area"), table_name="grantees")
    op.drop_index(op.f("idx_grantees_website"), table_name="grantees")
    op.drop_table("grantees")
    op.drop_index(op.f("idx_crawl_runs_run_date"), table_name="crawl_runs")
    op.drop_index(op.f("idx_crawl_runs_status"), table_name="crawl_runs")
    op.drop_table("crawl_runs")
    op.drop_index(op.f("idx_edits_created"), table_name="edits")
    op.drop_index(op.f("idx_edits_source"), table_name="edits")
    op.drop_index(op.f("idx_edits_table_record"), table_name="edits")
    op.drop_index(op.f("idx_edits_user"), table_name="edits")
    op.drop_table("edits")
    op.drop_table("location_instagram")
    op.drop_table("website_instagram")
    op.drop_index(
        op.f("idx_crawl_event_occurrences_event"), table_name="crawl_event_occurrences"
    )
    op.drop_index(
        op.f("idx_crawl_event_occurrences_start_date"),
        table_name="crawl_event_occurrences",
    )
    op.drop_table("crawl_event_occurrences")
    op.drop_index(op.f("idx_conflicts_created"), table_name="conflicts")
    op.drop_index(op.f("idx_conflicts_status"), table_name="conflicts")
    op.drop_index(op.f("idx_conflicts_table_record"), table_name="conflicts")
    op.drop_table("conflicts")
    op.drop_index(op.f("idx_website_tags_website"), table_name="website_tags")
    op.drop_table("website_tags")
    op.drop_index(op.f("idx_websites_disabled"), table_name="websites")
    op.drop_index(op.f("idx_websites_last_crawled"), table_name="websites")
    op.drop_index(op.f("idx_websites_name"), table_name="websites")
    op.drop_table("websites")
    op.drop_table("instagram_accounts")
    op.drop_index(op.f("idx_website_urls_website"), table_name="website_urls")
    op.drop_table("website_urls")
    op.drop_index(
        op.f("idx_website_locations_location"), table_name="website_locations"
    )
    op.drop_index(op.f("idx_website_locations_website"), table_name="website_locations")
    op.drop_table("website_locations")
    op.drop_index(op.f("idx_crawl_event_tags_event"), table_name="crawl_event_tags")
    op.drop_index(op.f("idx_crawl_event_tags_tag"), table_name="crawl_event_tags")
    op.drop_table("crawl_event_tags")
    op.drop_index(op.f("idx_feedback_created_at"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_table("sync_state")
    op.drop_index(op.f("idx_crawl_events_content_hash"), table_name="crawl_events")
    op.drop_index(op.f("idx_crawl_events_crawl_result"), table_name="crawl_events")
    op.drop_index(op.f("idx_crawl_events_location_id"), table_name="crawl_events")
    op.drop_index(op.f("idx_crawl_events_location_name"), table_name="crawl_events")
    op.drop_index(op.f("idx_crawl_events_name"), table_name="crawl_events")
    op.drop_table("crawl_events")
    op.add_column(
        "crawl_results", sa.Column("crawl_job_id", sa.Integer(), nullable=False)
    )
    op.add_column("crawl_results", sa.Column("source_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("crawl_results_crawl_run_id_filename_key"), "crawl_results", type_="unique"
    )
    op.drop_index(op.f("idx_crawl_results_crawl_run"), table_name="crawl_results")
    op.drop_index(op.f("idx_crawl_results_status"), table_name="crawl_results")
    op.drop_index(op.f("idx_crawl_results_website"), table_name="crawl_results")
    op.create_unique_constraint(None, "crawl_results", ["crawl_job_id", "source_id"])
    op.drop_constraint(
        op.f("crawl_results_crawl_run_id_fkey"), "crawl_results", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("crawl_results_website_id_fkey"), "crawl_results", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "crawl_results", "sources", ["source_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "crawl_results",
        "crawl_jobs",
        ["crawl_job_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("crawl_results", "event_count")
    op.drop_column("crawl_results", "filename")
    op.drop_column("crawl_results", "crawl_run_id")
    op.drop_column("crawl_results", "crawled_content")
    op.drop_column("crawl_results", "website_id")
    op.drop_column("crawl_results", "extracted_content")
    op.drop_index(
        op.f("idx_event_occurrences_date_range"), table_name="event_occurrences"
    )
    op.drop_index(op.f("idx_event_occurrences_event"), table_name="event_occurrences")
    op.drop_index(
        op.f("idx_event_occurrences_start_date"), table_name="event_occurrences"
    )
    op.drop_column("event_occurrences", "sort_order")
    op.add_column(
        "event_sources", sa.Column("extracted_event_id", sa.Integer(), nullable=True)
    )
    op.add_column("event_sources", sa.Column("source_id", sa.Integer(), nullable=False))
    op.add_column(
        "event_sources",
        sa.Column(
            "trust_score",
            sa.Numeric(precision=2, scale=1, asdecimal=False),
            nullable=True,
        ),
    )
    op.drop_constraint(
        op.f("event_sources_event_id_crawl_event_id_key"),
        "event_sources",
        type_="unique",
    )
    op.drop_index(op.f("idx_event_sources_crawl_event"), table_name="event_sources")
    op.drop_index(op.f("idx_event_sources_event"), table_name="event_sources")
    op.create_unique_constraint(
        None, "event_sources", ["event_id", "extracted_event_id"]
    )
    op.drop_constraint(
        op.f("event_sources_crawl_event_id_fkey"), "event_sources", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "event_sources",
        "extracted_events",
        ["extracted_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "event_sources", "sources", ["source_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("event_sources", "crawl_event_id")
    op.drop_constraint(
        op.f("event_tags_event_id_tag_id_key"), "event_tags", type_="unique"
    )
    op.drop_index(op.f("idx_event_tags_event"), table_name="event_tags")
    op.drop_index(op.f("idx_event_tags_tag"), table_name="event_tags")
    op.drop_column("event_tags", "id")
    op.drop_index(op.f("idx_event_urls_event"), table_name="event_urls")
    op.drop_column("event_urls", "sort_order")
    op.add_column(
        "events",
        sa.Column(
            "status",
            sa.Enum("active", "archived", "draft", "cancelled", name="event_status"),
            server_default="active",
            nullable=False,
        ),
    )
    op.add_column("events", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True))
    op.alter_column("events", "location_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_index(op.f("idx_events_archived"), table_name="events")
    op.drop_index(op.f("idx_events_location"), table_name="events")
    op.drop_index(op.f("idx_events_name"), table_name="events")
    op.drop_index(op.f("idx_events_reviewed"), table_name="events")
    op.drop_index(op.f("idx_events_website"), table_name="events")
    op.drop_constraint(op.f("events_location_id_fkey"), "events", type_="foreignkey")
    op.drop_constraint(op.f("events_website_id_fkey"), "events", type_="foreignkey")
    op.create_foreign_key(
        None, "events", "locations", ["location_id"], ["id"], ondelete="RESTRICT"
    )
    op.drop_column("events", "suppressed")
    op.drop_column("events", "website_id")
    op.drop_column("events", "location_name")
    op.drop_column("events", "archived")
    op.drop_index(
        op.f("idx_location_alt_names_location"), table_name="location_alternate_names"
    )
    op.drop_index(
        op.f("idx_location_alt_names_name"), table_name="location_alternate_names"
    )
    op.drop_index(
        op.f("idx_location_alt_names_website"), table_name="location_alternate_names"
    )
    op.drop_constraint(
        op.f("location_alternate_names_website_id_fkey"),
        "location_alternate_names",
        type_="foreignkey",
    )
    op.drop_column("location_alternate_names", "website_id")
    op.drop_index(op.f("idx_location_tags_location"), table_name="location_tags")
    op.drop_index(op.f("idx_location_tags_tag"), table_name="location_tags")
    op.drop_constraint(
        op.f("location_tags_location_id_tag_id_key"), "location_tags", type_="unique"
    )
    op.drop_column("location_tags", "id")
    op.add_column(
        "locations", sa.Column("website_url", sa.String(length=500), nullable=True)
    )
    op.add_column(
        "locations",
        sa.Column(
            "type",
            sa.Enum("venue", "area", "meeting_point", name="location_type"),
            server_default="venue",
            nullable=False,
        ),
    )
    op.add_column("locations", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True))
    op.drop_index(op.f("idx_locations_coords"), table_name="locations")
    op.drop_index(op.f("idx_locations_name"), table_name="locations")
    op.drop_index(op.f("idx_locations_short_name"), table_name="locations")
    op.add_column("tag_rules", sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True))
    op.drop_index(op.f("idx_tag_rules_pattern"), table_name="tag_rules")
    op.drop_index(op.f("idx_tag_rules_rule_type"), table_name="tag_rules")
    op.drop_index(op.f("idx_tags_name"), table_name="tags")
    op.drop_index(op.f("idx_users_email"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("idx_tags_name"), "tags", ["name"], unique=False)
    op.create_index(
        op.f("idx_tag_rules_rule_type"), "tag_rules", ["rule_type"], unique=False
    )
    op.create_index(
        op.f("idx_tag_rules_pattern"), "tag_rules", ["pattern"], unique=False
    )
    op.drop_column("tag_rules", "deleted_at")
    op.create_index(
        op.f("idx_locations_short_name"), "locations", ["short_name"], unique=False
    )
    op.create_index(op.f("idx_locations_name"), "locations", ["name"], unique=False)
    op.create_index(
        op.f("idx_locations_coords"), "locations", ["lat", "lng"], unique=False
    )
    op.drop_column("locations", "deleted_at")
    op.drop_column("locations", "type")
    op.drop_column("locations", "website_url")
    op.add_column(
        "location_tags",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_unique_constraint(
        op.f("location_tags_location_id_tag_id_key"),
        "location_tags",
        ["location_id", "tag_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("idx_location_tags_tag"), "location_tags", ["tag_id"], unique=False
    )
    op.create_index(
        op.f("idx_location_tags_location"),
        "location_tags",
        ["location_id"],
        unique=False,
    )
    op.add_column(
        "location_alternate_names",
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("location_alternate_names_website_id_fkey"),
        "location_alternate_names",
        "websites",
        ["website_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("idx_location_alt_names_website"),
        "location_alternate_names",
        ["website_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_location_alt_names_name"),
        "location_alternate_names",
        ["alternate_name"],
        unique=False,
    )
    op.create_index(
        op.f("idx_location_alt_names_location"),
        "location_alternate_names",
        ["location_id"],
        unique=False,
    )
    op.add_column(
        "events",
        sa.Column(
            "archived",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "location_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "events",
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "events",
        sa.Column(
            "suppressed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "events", type_="foreignkey")
    op.create_foreign_key(
        op.f("events_website_id_fkey"),
        "events",
        "websites",
        ["website_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("events_location_id_fkey"),
        "events",
        "locations",
        ["location_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(op.f("idx_events_website"), "events", ["website_id"], unique=False)
    op.create_index(op.f("idx_events_reviewed"), "events", ["reviewed"], unique=False)
    op.create_index(op.f("idx_events_name"), "events", ["name"], unique=False)
    op.create_index(
        op.f("idx_events_location"), "events", ["location_id"], unique=False
    )
    op.create_index(op.f("idx_events_archived"), "events", ["archived"], unique=False)
    op.alter_column("events", "location_id", existing_type=sa.INTEGER(), nullable=True)
    op.drop_column("events", "deleted_at")
    op.drop_column("events", "status")
    op.add_column(
        "event_urls",
        sa.Column(
            "sort_order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("idx_event_urls_event"), "event_urls", ["event_id"], unique=False
    )
    op.add_column(
        "event_tags", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.create_index(op.f("idx_event_tags_tag"), "event_tags", ["tag_id"], unique=False)
    op.create_index(
        op.f("idx_event_tags_event"), "event_tags", ["event_id"], unique=False
    )
    op.create_unique_constraint(
        op.f("event_tags_event_id_tag_id_key"),
        "event_tags",
        ["event_id", "tag_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.add_column(
        "event_sources",
        sa.Column("crawl_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "event_sources", type_="foreignkey")
    op.drop_constraint(None, "event_sources", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_sources_crawl_event_id_fkey"),
        "event_sources",
        "crawl_events",
        ["crawl_event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "event_sources", type_="unique")
    op.create_index(
        op.f("idx_event_sources_event"), "event_sources", ["event_id"], unique=False
    )
    op.create_index(
        op.f("idx_event_sources_crawl_event"),
        "event_sources",
        ["crawl_event_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("event_sources_event_id_crawl_event_id_key"),
        "event_sources",
        ["event_id", "crawl_event_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("event_sources", "trust_score")
    op.drop_column("event_sources", "source_id")
    op.drop_column("event_sources", "extracted_event_id")
    op.add_column(
        "event_occurrences",
        sa.Column(
            "sort_order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("idx_event_occurrences_start_date"),
        "event_occurrences",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_occurrences_event"),
        "event_occurrences",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_event_occurrences_date_range"),
        "event_occurrences",
        ["start_date", "end_date"],
        unique=False,
    )
    op.add_column(
        "crawl_results",
        sa.Column("extracted_content", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "crawl_results",
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "crawl_results",
        sa.Column("crawled_content", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "crawl_results",
        sa.Column("crawl_run_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "crawl_results",
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "crawl_results",
        sa.Column(
            "event_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "crawl_results", type_="foreignkey")
    op.drop_constraint(None, "crawl_results", type_="foreignkey")
    op.create_foreign_key(
        op.f("crawl_results_website_id_fkey"),
        "crawl_results",
        "websites",
        ["website_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("crawl_results_crawl_run_id_fkey"),
        "crawl_results",
        "crawl_runs",
        ["crawl_run_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "crawl_results", type_="unique")
    op.create_index(
        op.f("idx_crawl_results_website"), "crawl_results", ["website_id"], unique=False
    )
    op.create_index(
        op.f("idx_crawl_results_status"), "crawl_results", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_crawl_results_crawl_run"),
        "crawl_results",
        ["crawl_run_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("crawl_results_crawl_run_id_filename_key"),
        "crawl_results",
        ["crawl_run_id", "filename"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("crawl_results", "source_id")
    op.drop_column("crawl_results", "crawl_job_id")
    op.create_table(
        "crawl_events",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("crawl_result_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "short_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("emoji", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
        sa.Column(
            "location_name", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "sublocation", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("location_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("url", sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
        sa.Column(
            "raw_data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "content_hash", sa.CHAR(length=64), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_result_id"],
            ["crawl_results.id"],
            name=op.f("crawl_events_crawl_result_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("crawl_events_pkey")),
    )
    op.create_index(
        op.f("idx_crawl_events_name"), "crawl_events", ["name"], unique=False
    )
    op.create_index(
        op.f("idx_crawl_events_location_name"),
        "crawl_events",
        ["location_name"],
        unique=False,
    )
    op.create_index(
        op.f("idx_crawl_events_location_id"),
        "crawl_events",
        ["location_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_crawl_events_crawl_result"),
        "crawl_events",
        ["crawl_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_crawl_events_content_hash"),
        "crawl_events",
        ["content_hash"],
        unique=False,
    )
    op.create_table(
        "sync_state",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "source",
            postgresql.ENUM("local", "website", name="sync_source"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_synced_edit_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_sync_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("sync_state_pkey")),
        sa.UniqueConstraint(
            "source",
            name=op.f("sync_state_source_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "page_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("feedback_pkey")),
    )
    op.create_index(
        op.f("idx_feedback_created_at"), "feedback", ["created_at"], unique=False
    )
    op.create_table(
        "crawl_event_tags",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("crawl_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["crawl_event_id"],
            ["crawl_events.id"],
            name=op.f("crawl_event_tags_crawl_event_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("crawl_event_tags_pkey")),
    )
    op.create_index(
        op.f("idx_crawl_event_tags_tag"), "crawl_event_tags", ["tag"], unique=False
    )
    op.create_index(
        op.f("idx_crawl_event_tags_event"),
        "crawl_event_tags",
        ["crawl_event_id"],
        unique=False,
    )
    op.create_table(
        "website_locations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("location_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("website_locations_location_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("website_locations_website_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("website_locations_pkey")),
        sa.UniqueConstraint(
            "website_id",
            "location_id",
            name=op.f("website_locations_website_id_location_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_website_locations_website"),
        "website_locations",
        ["website_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_website_locations_location"),
        "website_locations",
        ["location_id"],
        unique=False,
    )
    op.create_table(
        "website_urls",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(length=2000), autoincrement=False, nullable=False),
        sa.Column("js_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "sort_order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("website_urls_website_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("website_urls_pkey")),
    )
    op.create_index(
        op.f("idx_website_urls_website"), "website_urls", ["website_id"], unique=False
    )
    op.create_table(
        "instagram_accounts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "handle", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "description", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("instagram_accounts_pkey")),
        sa.UniqueConstraint(
            "handle",
            name=op.f("instagram_accounts_handle_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "websites",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "base_url", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("crawl_frequency", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "selector", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("num_clicks", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("js_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "keywords", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "max_pages",
            sa.INTEGER(),
            server_default=sa.text("30"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("max_batches", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "disabled",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "source_type",
            postgresql.ENUM("primary", "aggregator", name="source_type"),
            server_default=sa.text("'primary'::source_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("crawl_after", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "force_crawl",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_crawled_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "delay_before_return_html", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "content_filter_threshold",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("scan_full_page", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "remove_overlay_elements", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "javascript_enabled", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column("text_mode", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("light_mode", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("use_stealth", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "scroll_delay",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("crawl_timeout", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "crawl_frequency_locked",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("process_images", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "crawl_mode",
            postgresql.ENUM("browser", "json_api", name="crawl_mode"),
            server_default=sa.text("'browser'::crawl_mode"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "json_api_config",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("websites_pkey")),
    )
    op.create_index(op.f("idx_websites_name"), "websites", ["name"], unique=False)
    op.create_index(
        op.f("idx_websites_last_crawled"), "websites", ["last_crawled_at"], unique=False
    )
    op.create_index(
        op.f("idx_websites_disabled"), "websites", ["disabled"], unique=False
    )
    op.create_table(
        "website_tags",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
            name=op.f("website_tags_tag_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("website_tags_website_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("website_tags_pkey")),
        sa.UniqueConstraint(
            "website_id",
            "tag_id",
            name=op.f("website_tags_website_id_tag_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_website_tags_website"), "website_tags", ["website_id"], unique=False
    )
    op.create_table(
        "conflicts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("local_edit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("website_edit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "table_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("record_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "field_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column("local_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("website_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "resolved_local",
                "resolved_website",
                "resolved_merged",
                name="conflict_status",
            ),
            server_default=sa.text("'pending'::conflict_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("resolved_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("resolved_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "resolved_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["local_edit_id"],
            ["edits.id"],
            name=op.f("conflicts_local_edit_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"],
            ["users.id"],
            name=op.f("conflicts_resolved_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["website_edit_id"],
            ["edits.id"],
            name=op.f("conflicts_website_edit_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conflicts_pkey")),
    )
    op.create_index(
        op.f("idx_conflicts_table_record"),
        "conflicts",
        ["table_name", "record_id"],
        unique=False,
    )
    op.create_index(op.f("idx_conflicts_status"), "conflicts", ["status"], unique=False)
    op.create_index(
        op.f("idx_conflicts_created"), "conflicts", ["created_at"], unique=False
    )
    op.create_table(
        "crawl_event_occurrences",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("crawl_event_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("start_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "start_time", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("end_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "end_time", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "sort_order",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_event_id"],
            ["crawl_events.id"],
            name=op.f("crawl_event_occurrences_crawl_event_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("crawl_event_occurrences_pkey")),
    )
    op.create_index(
        op.f("idx_crawl_event_occurrences_start_date"),
        "crawl_event_occurrences",
        ["start_date"],
        unique=False,
    )
    op.create_index(
        op.f("idx_crawl_event_occurrences_event"),
        "crawl_event_occurrences",
        ["crawl_event_id"],
        unique=False,
    )
    op.create_table(
        "website_instagram",
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("instagram_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["instagram_id"],
            ["instagram_accounts.id"],
            name=op.f("website_instagram_instagram_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("website_instagram_website_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "website_id", "instagram_id", name=op.f("website_instagram_pkey")
        ),
    )
    op.create_table(
        "location_instagram",
        sa.Column("location_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("instagram_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["instagram_id"],
            ["instagram_accounts.id"],
            name=op.f("location_instagram_instagram_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("location_instagram_location_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "location_id", "instagram_id", name=op.f("location_instagram_pkey")
        ),
    )
    op.create_table(
        "edits",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("edit_uuid", sa.CHAR(length=36), autoincrement=False, nullable=False),
        sa.Column(
            "table_name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("record_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "field_name", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "action",
            postgresql.ENUM("INSERT", "UPDATE", "DELETE", name="edit_action"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("old_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("new_value", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "source",
            postgresql.ENUM("local", "website", "crawl", name="edit_source"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "editor_ip", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column(
            "editor_user_agent",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "editor_info", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "applied_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("edits_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("edits_pkey")),
        sa.UniqueConstraint(
            "edit_uuid",
            name=op.f("edits_edit_uuid_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("idx_edits_user"), "edits", ["user_id"], unique=False)
    op.create_index(
        op.f("idx_edits_table_record"),
        "edits",
        ["table_name", "record_id"],
        unique=False,
    )
    op.create_index(op.f("idx_edits_source"), "edits", ["source"], unique=False)
    op.create_index(op.f("idx_edits_created"), "edits", ["created_at"], unique=False)
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("run_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("running", "completed", "failed", name="crawl_run_status"),
            server_default=sa.text("'running'::crawl_run_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "completed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("crawl_runs_pkey")),
        sa.UniqueConstraint(
            "run_date",
            name=op.f("crawl_runs_run_date_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_crawl_runs_status"), "crawl_runs", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_crawl_runs_run_date"), "crawl_runs", ["run_date"], unique=False
    )
    op.create_table(
        "grantees",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("area", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.Column("website_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "exclusion_reason",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("grantees_website_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("grantees_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("grantees_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_grantees_website"), "grantees", ["website_id"], unique=False
    )
    op.create_index(op.f("idx_grantees_area"), "grantees", ["area"], unique=False)
    op.drop_table("extracted_events")
    op.drop_table("crawl_contents")
    op.drop_table("source_urls")
    op.drop_table("crawl_configs")
    op.drop_table("sources")
    op.drop_table("crawl_jobs")
    # ### end Alembic commands ###
