"""initial schema

Revision ID: 94f350d270a4
Revises: 
Create Date: 2026-03-24 11:43:00.115722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94f350d270a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.Enum('running', 'completed', 'failed', name='crawl_job_status'), server_default='running', nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('very_short_name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('alt_emoji', sa.String(length=10), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('type', sa.Enum('venue', 'area', 'meeting_point', name='location_type'), server_default='venue', nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('crawler', 'api', 'user_submission', 'partner_feed', name='source_type'), nullable=False),
    sa.Column('trust_level', sa.Numeric(precision=2, scale=1, asdecimal=False), nullable=True),
    sa.Column('disabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rule_type', sa.Enum('rewrite', 'exclude', 'remove', name='tag_rule_type'), nullable=False),
    sa.Column('pattern', sa.String(length=100), nullable=False),
    sa.Column('replacement', sa.String(length=100), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_type', 'pattern')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('crawl_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('default_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('crawl_frequency', sa.Integer(), nullable=False),
    sa.Column('crawl_frequency_locked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('crawl_after', sa.Date(), nullable=True),
    sa.Column('force_crawl', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('crawl_mode', sa.Enum('browser', 'json_api', name='crawl_mode'), server_default='browser', nullable=False),
    sa.Column('selector', sa.String(length=500), nullable=True),
    sa.Column('num_clicks', sa.Integer(), nullable=True),
    sa.Column('js_code', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=255), nullable=True),
    sa.Column('max_pages', sa.Integer(), server_default='30', nullable=False),
    sa.Column('max_batches', sa.Integer(), nullable=True),
    sa.Column('json_api_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delay_before_return_html', sa.Integer(), nullable=True),
    sa.Column('content_filter_threshold', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=True),
    sa.Column('scan_full_page', sa.Boolean(), nullable=True),
    sa.Column('remove_overlay_elements', sa.Boolean(), nullable=True),
    sa.Column('javascript_enabled', sa.Boolean(), nullable=True),
    sa.Column('text_mode', sa.Boolean(), nullable=True),
    sa.Column('light_mode', sa.Boolean(), nullable=True),
    sa.Column('use_stealth', sa.Boolean(), nullable=True),
    sa.Column('scroll_delay', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=True),
    sa.Column('crawl_timeout', sa.Integer(), nullable=True),
    sa.Column('process_images', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('crawl_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crawl_job_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'crawled', 'extracted', 'processed', 'failed', name='crawl_result_status'), server_default='pending', nullable=False),
    sa.Column('crawled_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('extracted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_job_id', 'source_id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sublocation', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', 'draft', 'cancelled', name='event_status'), server_default='active', nullable=False),
    sa.Column('reviewed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_alternate_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('alternate_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location_tags',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'tag_id')
    )
    op.create_table('source_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('js_code', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crawl_contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crawl_result_id', sa.Integer(), nullable=False),
    sa.Column('crawled_content', sa.Text(), nullable=True),
    sa.Column('extracted_content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_result_id'], ['crawl_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_result_id')
    )
    op.create_table('event_occurrences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('end_time', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_tags',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'tag_id')
    )
    op.create_table('event_urls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crawl_result_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('sublocation', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=True),
    sa.Column('occurrences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_result_id'], ['crawl_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('extracted_event_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Numeric(precision=2, scale=1, asdecimal=False), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['extracted_event_id'], ['extracted_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'extracted_event_id')
    )
    op.create_table('extracted_event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extracted_event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('created', 'merged', 'skipped_no_location', 'skipped_no_occurrences', 'skipped_duplicate', name='extracted_event_status'), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extracted_event_id'], ['extracted_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extracted_event_logs')
    op.drop_table('event_sources')
    op.drop_table('extracted_events')
    op.drop_table('event_urls')
    op.drop_table('event_tags')
    op.drop_table('event_occurrences')
    op.drop_table('crawl_contents')
    op.drop_table('source_urls')
    op.drop_table('location_tags')
    op.drop_table('location_alternate_names')
    op.drop_table('events')
    op.drop_table('crawl_results')
    op.drop_table('crawl_configs')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('tag_rules')
    op.drop_table('sources')
    op.drop_table('locations')
    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
