"""initial schema

Revision ID: e9fd649ee871
Revises:
Create Date: 2026-03-16 16:21:53.567179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9fd649ee871"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("running", "completed", "failed", name="crawl_run_status"),
            server_default="running",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_date"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("page_url", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instagram_accounts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("handle", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("handle"),
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=True),
        sa.Column("very_short_name", sa.String(length=50), nullable=True),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "lat", sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True
        ),
        sa.Column(
            "lng", sa.Numeric(precision=10, scale=6, asdecimal=False), nullable=True
        ),
        sa.Column("emoji", sa.String(length=10), nullable=True),
        sa.Column("alt_emoji", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "source", sa.Enum("local", "website", name="sync_source"), nullable=False
        ),
        sa.Column("last_synced_edit_id", sa.Integer(), nullable=True),
        sa.Column("last_sync_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source"),
    )
    op.create_table(
        "tag_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "rule_type",
            sa.Enum("rewrite", "exclude", "remove", name="tag_rule_type"),
            nullable=False,
        ),
        sa.Column("pattern", sa.String(length=100), nullable=False),
        sa.Column("replacement", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_type", "pattern"),
    )
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "websites",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("crawl_frequency", sa.Integer(), nullable=True),
        sa.Column("selector", sa.String(length=500), nullable=True),
        sa.Column("num_clicks", sa.Integer(), nullable=True),
        sa.Column("js_code", sa.Text(), nullable=True),
        sa.Column("keywords", sa.String(length=255), nullable=True),
        sa.Column("max_pages", sa.Integer(), server_default="30", nullable=True),
        sa.Column("max_batches", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("disabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "source_type",
            sa.Enum("primary", "aggregator", name="source_type"),
            server_default="primary",
            nullable=False,
        ),
        sa.Column("crawl_after", sa.Date(), nullable=True),
        sa.Column("force_crawl", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(), nullable=True),
        sa.Column("delay_before_return_html", sa.Integer(), nullable=True),
        sa.Column(
            "content_filter_threshold",
            sa.Numeric(precision=3, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column("scan_full_page", sa.Boolean(), nullable=True),
        sa.Column("remove_overlay_elements", sa.Boolean(), nullable=True),
        sa.Column("javascript_enabled", sa.Boolean(), nullable=True),
        sa.Column("text_mode", sa.Boolean(), nullable=True),
        sa.Column("light_mode", sa.Boolean(), nullable=True),
        sa.Column("use_stealth", sa.Boolean(), nullable=True),
        sa.Column(
            "scroll_delay",
            sa.Numeric(precision=3, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column("crawl_timeout", sa.Integer(), nullable=True),
        sa.Column(
            "crawl_frequency_locked",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("process_images", sa.Boolean(), nullable=True),
        sa.Column(
            "crawl_mode",
            sa.Enum("browser", "json_api", name="crawl_mode"),
            server_default="browser",
            nullable=False,
        ),
        sa.Column(
            "json_api_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_run_id", sa.Integer(), nullable=False),
        sa.Column("website_id", sa.Integer(), nullable=True),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("event_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "crawled",
                "extracted",
                "processed",
                "failed",
                name="crawl_result_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("crawled_content", sa.Text(), nullable=True),
        sa.Column("extracted_content", sa.Text(), nullable=True),
        sa.Column("crawled_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("extracted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("processed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_run_id"], ["crawl_runs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crawl_run_id", "filename"),
    )
    op.create_table(
        "edits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("edit_uuid", sa.CHAR(length=36), nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column(
            "action",
            sa.Enum("INSERT", "UPDATE", "DELETE", name="edit_action"),
            nullable=False,
        ),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("local", "website", "crawl", name="edit_source"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("editor_ip", sa.String(length=45), nullable=True),
        sa.Column("editor_user_agent", sa.String(length=500), nullable=True),
        sa.Column("editor_info", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("edit_uuid"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("emoji", sa.String(length=10), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("sublocation", sa.String(length=255), nullable=True),
        sa.Column("website_id", sa.Integer(), nullable=True),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("suppressed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("reviewed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grantees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("area", sa.String(length=100), nullable=True),
        sa.Column("website_id", sa.Integer(), nullable=True),
        sa.Column("exclusion_reason", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "location_alternate_names",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("alternate_name", sa.String(length=255), nullable=False),
        sa.Column("website_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "location_instagram",
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("instagram_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instagram_id"], ["instagram_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("location_id", "instagram_id"),
    )
    op.create_table(
        "location_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "tag_id"),
    )
    op.create_table(
        "website_instagram",
        sa.Column("website_id", sa.Integer(), nullable=False),
        sa.Column("instagram_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instagram_id"], ["instagram_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("website_id", "instagram_id"),
    )
    op.create_table(
        "website_locations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("website_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("website_id", "location_id"),
    )
    op.create_table(
        "website_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("website_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("website_id", "tag_id"),
    )
    op.create_table(
        "website_urls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("website_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("js_code", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["website_id"], ["websites.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conflicts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("local_edit_id", sa.Integer(), nullable=False),
        sa.Column("website_edit_id", sa.Integer(), nullable=False),
        sa.Column("table_name", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("field_name", sa.String(length=100), nullable=True),
        sa.Column("local_value", sa.Text(), nullable=True),
        sa.Column("website_value", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "resolved_local",
                "resolved_website",
                "resolved_merged",
                name="conflict_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("resolved_value", sa.Text(), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("resolved_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["local_edit_id"], ["edits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["website_edit_id"], ["edits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_result_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("emoji", sa.String(length=10), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("sublocation", sa.String(length=255), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_hash", sa.CHAR(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_result_id"], ["crawl_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_occurrences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.String(length=20), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("end_time", sa.String(length=20), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "tag_id"),
    )
    op.create_table(
        "event_urls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_event_occurrences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_event_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.String(length=20), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("end_time", sa.String(length=20), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["crawl_event_id"], ["crawl_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "crawl_event_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("crawl_event_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["crawl_event_id"], ["crawl_events.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "event_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("crawl_event_id", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["crawl_event_id"], ["crawl_events.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "crawl_event_id"),
    )
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Indexes (matching database/schema_postgres.sql)
    # ------------------------------------------------------------------

    # locations
    op.create_index("idx_locations_name", "locations", ["name"])
    op.create_index("idx_locations_short_name", "locations", ["short_name"])
    op.create_index("idx_locations_coords", "locations", ["lat", "lng"])

    # websites
    op.create_index("idx_websites_name", "websites", ["name"])
    op.create_index("idx_websites_last_crawled", "websites", ["last_crawled_at"])
    op.create_index("idx_websites_disabled", "websites", ["disabled"])

    # website_urls
    op.create_index("idx_website_urls_website", "website_urls", ["website_id"])

    # website_locations
    op.create_index(
        "idx_website_locations_website", "website_locations", ["website_id"]
    )
    op.create_index(
        "idx_website_locations_location", "website_locations", ["location_id"]
    )

    # location_alternate_names
    op.create_index(
        "idx_location_alt_names_location", "location_alternate_names", ["location_id"]
    )
    op.create_index(
        "idx_location_alt_names_name", "location_alternate_names", ["alternate_name"]
    )
    op.create_index(
        "idx_location_alt_names_website", "location_alternate_names", ["website_id"]
    )

    # website_tags
    op.create_index("idx_website_tags_website", "website_tags", ["website_id"])

    # events
    op.create_index("idx_events_name", "events", ["name"])
    op.create_index("idx_events_location", "events", ["location_id"])
    op.create_index("idx_events_website", "events", ["website_id"])
    op.create_index("idx_events_archived", "events", ["archived"])
    op.create_index("idx_events_reviewed", "events", ["reviewed"])

    # event_occurrences
    op.create_index("idx_event_occurrences_event", "event_occurrences", ["event_id"])
    op.create_index(
        "idx_event_occurrences_start_date", "event_occurrences", ["start_date"]
    )
    op.create_index(
        "idx_event_occurrences_date_range",
        "event_occurrences",
        ["start_date", "end_date"],
    )

    # event_urls
    op.create_index("idx_event_urls_event", "event_urls", ["event_id"])

    # tags
    op.create_index("idx_tags_name", "tags", ["name"])

    # location_tags
    op.create_index("idx_location_tags_location", "location_tags", ["location_id"])
    op.create_index("idx_location_tags_tag", "location_tags", ["tag_id"])

    # event_tags
    op.create_index("idx_event_tags_event", "event_tags", ["event_id"])
    op.create_index("idx_event_tags_tag", "event_tags", ["tag_id"])

    # crawl_runs
    op.create_index("idx_crawl_runs_status", "crawl_runs", ["status"])
    op.create_index("idx_crawl_runs_run_date", "crawl_runs", ["run_date"])

    # crawl_results
    op.create_index("idx_crawl_results_crawl_run", "crawl_results", ["crawl_run_id"])
    op.create_index("idx_crawl_results_website", "crawl_results", ["website_id"])
    op.create_index("idx_crawl_results_status", "crawl_results", ["status"])

    # crawl_events
    op.create_index(
        "idx_crawl_events_crawl_result", "crawl_events", ["crawl_result_id"]
    )
    op.create_index("idx_crawl_events_name", "crawl_events", ["name"])
    op.create_index("idx_crawl_events_content_hash", "crawl_events", ["content_hash"])
    op.create_index("idx_crawl_events_location_name", "crawl_events", ["location_name"])
    op.create_index("idx_crawl_events_location_id", "crawl_events", ["location_id"])

    # crawl_event_occurrences
    op.create_index(
        "idx_crawl_event_occurrences_event",
        "crawl_event_occurrences",
        ["crawl_event_id"],
    )
    op.create_index(
        "idx_crawl_event_occurrences_start_date",
        "crawl_event_occurrences",
        ["start_date"],
    )

    # crawl_event_tags
    op.create_index(
        "idx_crawl_event_tags_event", "crawl_event_tags", ["crawl_event_id"]
    )
    op.create_index("idx_crawl_event_tags_tag", "crawl_event_tags", ["tag"])

    # event_sources
    op.create_index("idx_event_sources_event", "event_sources", ["event_id"])
    op.create_index(
        "idx_event_sources_crawl_event", "event_sources", ["crawl_event_id"]
    )

    # tag_rules
    op.create_index("idx_tag_rules_rule_type", "tag_rules", ["rule_type"])
    op.create_index("idx_tag_rules_pattern", "tag_rules", ["pattern"])

    # feedback
    op.create_index("idx_feedback_created_at", "feedback", ["created_at"])

    # users
    op.create_index("idx_users_email", "users", ["email"])

    # edits
    op.create_index("idx_edits_table_record", "edits", ["table_name", "record_id"])
    op.create_index("idx_edits_source", "edits", ["source"])
    op.create_index("idx_edits_created", "edits", ["created_at"])
    op.create_index("idx_edits_user", "edits", ["user_id"])

    # conflicts
    op.create_index("idx_conflicts_status", "conflicts", ["status"])
    op.create_index(
        "idx_conflicts_table_record", "conflicts", ["table_name", "record_id"]
    )
    op.create_index("idx_conflicts_created", "conflicts", ["created_at"])

    # grantees
    op.create_index("idx_grantees_area", "grantees", ["area"])
    op.create_index("idx_grantees_website", "grantees", ["website_id"])


def downgrade() -> None:
    """Downgrade schema."""
    # ------------------------------------------------------------------
    # Drop indexes
    # ------------------------------------------------------------------
    op.drop_index("idx_grantees_website", table_name="grantees")
    op.drop_index("idx_grantees_area", table_name="grantees")
    op.drop_index("idx_conflicts_created", table_name="conflicts")
    op.drop_index("idx_conflicts_table_record", table_name="conflicts")
    op.drop_index("idx_conflicts_status", table_name="conflicts")
    op.drop_index("idx_edits_user", table_name="edits")
    op.drop_index("idx_edits_created", table_name="edits")
    op.drop_index("idx_edits_source", table_name="edits")
    op.drop_index("idx_edits_table_record", table_name="edits")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_feedback_created_at", table_name="feedback")
    op.drop_index("idx_tag_rules_pattern", table_name="tag_rules")
    op.drop_index("idx_tag_rules_rule_type", table_name="tag_rules")
    op.drop_index("idx_event_sources_crawl_event", table_name="event_sources")
    op.drop_index("idx_event_sources_event", table_name="event_sources")
    op.drop_index("idx_crawl_event_tags_tag", table_name="crawl_event_tags")
    op.drop_index("idx_crawl_event_tags_event", table_name="crawl_event_tags")
    op.drop_index(
        "idx_crawl_event_occurrences_start_date", table_name="crawl_event_occurrences"
    )
    op.drop_index(
        "idx_crawl_event_occurrences_event", table_name="crawl_event_occurrences"
    )
    op.drop_index("idx_crawl_events_location_id", table_name="crawl_events")
    op.drop_index("idx_crawl_events_location_name", table_name="crawl_events")
    op.drop_index("idx_crawl_events_content_hash", table_name="crawl_events")
    op.drop_index("idx_crawl_events_name", table_name="crawl_events")
    op.drop_index("idx_crawl_events_crawl_result", table_name="crawl_events")
    op.drop_index("idx_crawl_results_status", table_name="crawl_results")
    op.drop_index("idx_crawl_results_website", table_name="crawl_results")
    op.drop_index("idx_crawl_results_crawl_run", table_name="crawl_results")
    op.drop_index("idx_crawl_runs_run_date", table_name="crawl_runs")
    op.drop_index("idx_crawl_runs_status", table_name="crawl_runs")
    op.drop_index("idx_event_tags_tag", table_name="event_tags")
    op.drop_index("idx_event_tags_event", table_name="event_tags")
    op.drop_index("idx_location_tags_tag", table_name="location_tags")
    op.drop_index("idx_location_tags_location", table_name="location_tags")
    op.drop_index("idx_tags_name", table_name="tags")
    op.drop_index("idx_event_urls_event", table_name="event_urls")
    op.drop_index("idx_event_occurrences_date_range", table_name="event_occurrences")
    op.drop_index("idx_event_occurrences_start_date", table_name="event_occurrences")
    op.drop_index("idx_event_occurrences_event", table_name="event_occurrences")
    op.drop_index("idx_events_reviewed", table_name="events")
    op.drop_index("idx_events_archived", table_name="events")
    op.drop_index("idx_events_website", table_name="events")
    op.drop_index("idx_events_location", table_name="events")
    op.drop_index("idx_events_name", table_name="events")
    op.drop_index("idx_website_tags_website", table_name="website_tags")
    op.drop_index(
        "idx_location_alt_names_website", table_name="location_alternate_names"
    )
    op.drop_index("idx_location_alt_names_name", table_name="location_alternate_names")
    op.drop_index(
        "idx_location_alt_names_location", table_name="location_alternate_names"
    )
    op.drop_index("idx_website_locations_location", table_name="website_locations")
    op.drop_index("idx_website_locations_website", table_name="website_locations")
    op.drop_index("idx_website_urls_website", table_name="website_urls")
    op.drop_index("idx_websites_disabled", table_name="websites")
    op.drop_index("idx_websites_last_crawled", table_name="websites")
    op.drop_index("idx_websites_name", table_name="websites")
    op.drop_index("idx_locations_coords", table_name="locations")
    op.drop_index("idx_locations_short_name", table_name="locations")
    op.drop_index("idx_locations_name", table_name="locations")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("event_sources")
    op.drop_table("crawl_event_tags")
    op.drop_table("crawl_event_occurrences")
    op.drop_table("event_urls")
    op.drop_table("event_tags")
    op.drop_table("event_occurrences")
    op.drop_table("crawl_events")
    op.drop_table("conflicts")
    op.drop_table("website_urls")
    op.drop_table("website_tags")
    op.drop_table("website_locations")
    op.drop_table("website_instagram")
    op.drop_table("location_tags")
    op.drop_table("location_instagram")
    op.drop_table("location_alternate_names")
    op.drop_table("grantees")
    op.drop_table("events")
    op.drop_table("edits")
    op.drop_table("crawl_results")
    op.drop_table("websites")
    op.drop_table("users")
    op.drop_table("tags")
    op.drop_table("tag_rules")
    op.drop_table("sync_state")
    op.drop_table("locations")
    op.drop_table("instagram_accounts")
    op.drop_table("feedback")
    op.drop_table("crawl_runs")
    # ### end Alembic commands ###

    # Drop enum types (use op.execute to avoid MissingGreenlet in async context)
    for enum_name in [
        "conflict_status",
        "crawl_result_status",
        "crawl_run_status",
        "edit_action",
        "edit_source",
        "source_type",
        "sync_source",
        "crawl_mode",
        "tag_rule_type",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
